/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Warren
 */
public class CheckOutSuccess extends javax.swing.JFrame {

    /**
     * Creates new form CheckOutSuccess
     */
    public CheckOutSuccess() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        CheckOutSuccess_COA = new javax.swing.JButton();
        CheckOutSuccess_CI = new javax.swing.JButton();
        CheckOutSuccess_Finish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Check Out Success");
        setBounds(new java.awt.Rectangle(500, 100, 500, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setDisplayedMnemonic('C');
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Successfully checked out book");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(86, 130, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        CheckOutSuccess_COA.setText("Checkout Another");
        CheckOutSuccess_COA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutSuccess_COAActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(62, 29, 62, 0);
        getContentPane().add(CheckOutSuccess_COA, gridBagConstraints);

        CheckOutSuccess_CI.setText("Check In");
        CheckOutSuccess_CI.setToolTipText("");
        CheckOutSuccess_CI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutSuccess_CIActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(62, 34, 62, 0);
        getContentPane().add(CheckOutSuccess_CI, gridBagConstraints);

        CheckOutSuccess_Finish.setText("Finish");
        CheckOutSuccess_Finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutSuccess_FinishActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(62, 34, 62, 43);
        getContentPane().add(CheckOutSuccess_Finish, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckOutSuccess_FinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutSuccess_FinishActionPerformed
        dispose();
    }//GEN-LAST:event_CheckOutSuccess_FinishActionPerformed

    private void CheckOutSuccess_COAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutSuccess_COAActionPerformed
        CheckOut co = new CheckOut();
        co.setVisible(true);
        dispose();
    }//GEN-LAST:event_CheckOutSuccess_COAActionPerformed

    private void CheckOutSuccess_CIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutSuccess_CIActionPerformed
        CheckIn ci = new CheckIn();
        ci.setVisible(true);
        dispose();
    }//GEN-LAST:event_CheckOutSuccess_CIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOutSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOutSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOutSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOutSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOutSuccess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckOutSuccess_CI;
    private javax.swing.JButton CheckOutSuccess_COA;
    private javax.swing.JButton CheckOutSuccess_Finish;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
