
import java.util.ArrayList;
import java.util.List;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Warren
 */
public class CheckOutResults extends javax.swing.JFrame {

    List<Book> bookList;
    ArrayList<String> bookListString = new ArrayList<>();
    Book[] books;
    String isbn10;
    
    
    /**
     * Creates new form CheckOutResults
     */
    public CheckOutResults(List<Book> listOfBooks) {
        this.bookList = listOfBooks;
        for(Book b : listOfBooks) {
            bookListString.add(b.toString());
        }

        books = bookList.toArray(new Book[bookList.size()]);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        CheckOutResults_List = new javax.swing.JList(books);
        CheckOutButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Check Out Results");
        setBounds(new java.awt.Rectangle(500, 100, 500, 500));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        CheckOutResults_List.setCellRenderer(new BookCellRenderer());
        jScrollPane1.setViewportView(CheckOutResults_List);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 438;
        gridBagConstraints.ipady = 368;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 15, 0, 15);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        CheckOutButton.setText("Check Out");
        CheckOutButton.setPreferredSize(new java.awt.Dimension(100, 60));
        CheckOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 61, 18, 0);
        getContentPane().add(CheckOutButton, gridBagConstraints);

        BackButton.setText("Back");
        BackButton.setPreferredSize(new java.awt.Dimension(100, 60));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.ipady = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 178, 18, 0);
        getContentPane().add(BackButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        CheckOut co = new CheckOut();
        co.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void CheckOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutButtonActionPerformed
        Book userSelectedBook = (Book)CheckOutResults_List.getSelectedValue();
        isbn10 = userSelectedBook.getIsbn();

        CheckOutVerify cov = new CheckOutVerify(isbn10);
        cov.setVisible(true);
        dispose();
    }//GEN-LAST:event_CheckOutButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CheckOutButton;
    private javax.swing.JList CheckOutResults_List;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
