import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Warren
 */
public class CheckInResults extends javax.swing.JFrame {

    private final String url = "jdbc:postgresql://localhost:5434/postgres";
    private final String user = "zpillman";
    private final String password = "password";

    String isbn10;
    int loan_id;

    BookLoan[] bookLoans;

    /**
     * Creates new form CheckInResults
     */
    public CheckInResults(List<BookLoan> bookLoans) {
        this.bookLoans = bookLoans.toArray(new BookLoan[bookLoans.size()]);
        initComponents();
    }

    public Connection connect() throws SQLException {
        return DriverManager.getConnection(url, user, password);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        CheckInResults_List = new javax.swing.JList(bookLoans);
        CheckInResults_CI = new javax.swing.JButton();
        CheckInResults_Back = new javax.swing.JButton();
        jScrollBar2 = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Check In Results");
        setBounds(new java.awt.Rectangle(500, 100, 500, 500));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        CheckInResults_List.setCellRenderer(new BookLoanCellRenderer());
        jScrollPane1.setViewportView(CheckInResults_List);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 438;
        gridBagConstraints.ipady = 368;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 15, 0, 15);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        CheckInResults_CI.setText("Check In");
        CheckInResults_CI.setPreferredSize(new java.awt.Dimension(100, 60));
        CheckInResults_CI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInResults_CIActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 61, 18, 0);
        getContentPane().add(CheckInResults_CI, gridBagConstraints);

        CheckInResults_Back.setText("Back");
        CheckInResults_Back.setName(""); // NOI18N
        CheckInResults_Back.setNextFocusableComponent(this);
        CheckInResults_Back.setPreferredSize(new java.awt.Dimension(100, 60));
        CheckInResults_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInResults_BackActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.ipady = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 178, 18, 0);
        getContentPane().add(CheckInResults_Back, gridBagConstraints);
        getContentPane().add(jScrollBar2, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents
// BACK BUTTON
    private void CheckInResults_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInResults_BackActionPerformed
        CheckIn ci = new CheckIn();
        ci.setVisible(true);
        dispose();
//setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_CheckInResults_BackActionPerformed

    private void CheckInResults_CIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInResults_CIActionPerformed
        //get the user selected option from the list
        BookLoan userSelectedOption = (BookLoan) CheckInResults_List.getSelectedValue();

        checkInBook(userSelectedOption.getLoanId(), userSelectedOption.getIsbn());

        CheckInSuccess cis = new CheckInSuccess();
        cis.setVisible(true);
        dispose();
    }//GEN-LAST:event_CheckInResults_CIActionPerformed

    public void checkInBook(int loan_id, String isbn10) {
        String updateBookLoansDateInSQL = "UPDATE Book_Loans "
            + "SET date_in = CURRENT_DATE "
            + "WHERE Book_Loans.loan_id = ?";

        try (Connection conn = connect(); PreparedStatement pstmt = conn.prepareStatement(updateBookLoansDateInSQL)) {
            pstmt.setInt(1, loan_id);

            ResultSet rs = pstmt.executeQuery();

            while(rs.next()) {
                System.out.println("Successful Update");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

        String updateBooksIsCheckedOutSQL = "UPDATE Book SET is_checked_out = false "
            + "WHERE Book.isbn = ?";

        try (Connection conn = connect(); PreparedStatement pstmt = conn.prepareStatement(updateBooksIsCheckedOutSQL)) {
            pstmt.setString(1, isbn10);

            ResultSet rs = pstmt.executeQuery();

            while(rs.next()) {
                System.out.println("Successful Update");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckInResults_Back;
    private javax.swing.JButton CheckInResults_CI;
    private javax.swing.JList CheckInResults_List;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
