/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Warren
 */
public class CheckInSuccess extends javax.swing.JFrame {

    /**
     * Creates new form CheckInSuccess
     */
    public CheckInSuccess() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        CheckInSuccess_CIA = new javax.swing.JButton();
        CheckInSuccess_Finish = new javax.swing.JButton();
        CheckInSuccess_CO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Check In Success");
        setBounds(new java.awt.Rectangle(500, 100, 500, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Succesfully checked in book");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(87, 168, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        CheckInSuccess_CIA.setText("Check In Another");
        CheckInSuccess_CIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInSuccess_CIAActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(61, 29, 62, 0);
        getContentPane().add(CheckInSuccess_CIA, gridBagConstraints);

        CheckInSuccess_Finish.setText("Finish");
        CheckInSuccess_Finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInSuccess_FinishActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(61, 17, 62, 43);
        getContentPane().add(CheckInSuccess_Finish, gridBagConstraints);

        CheckInSuccess_CO.setText("Check Out");
        CheckInSuccess_CO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInSuccess_COActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(61, 35, 62, 0);
        getContentPane().add(CheckInSuccess_CO, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckInSuccess_FinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInSuccess_FinishActionPerformed
        dispose();
    }//GEN-LAST:event_CheckInSuccess_FinishActionPerformed

    private void CheckInSuccess_CIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInSuccess_CIAActionPerformed
        CheckIn ci = new CheckIn();
        ci.setVisible(true);
        dispose();
    }//GEN-LAST:event_CheckInSuccess_CIAActionPerformed

    private void CheckInSuccess_COActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInSuccess_COActionPerformed
        CheckOut co = new CheckOut();
        co.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_CheckInSuccess_COActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckInSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckInSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckInSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckInSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckInSuccess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckInSuccess_CIA;
    private javax.swing.JButton CheckInSuccess_CO;
    private javax.swing.JButton CheckInSuccess_Finish;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
