/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.Array;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Warren
 */
public class Library extends javax.swing.JFrame {

  private final String url = "jdbc:postgresql://localhost:5434/postgres";
  private final String user = "zpillman";
  private final String password = "password";

  /**
   * Creates new form Library
   */
  public Library() {
    initComponents();
  }

  public Connection connect() throws SQLException {
    return DriverManager.getConnection(url, user, password);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    Library_CI = new javax.swing.JButton();
    Library_CO = new javax.swing.JButton();
    Library_NewUser = new javax.swing.JButton();
    Library_ViewFines = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Library");
    setBounds(new java.awt.Rectangle(500, 100, 1000, 1000));

    jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
    jLabel1.setText("Welcome to the Library");

    Library_CI.setText("Check In");
    Library_CI.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Library_CIActionPerformed(evt);
      }
    });

    Library_CO.setText("Check Out");
    Library_CO.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Library_COActionPerformed(evt);
      }
    });

    Library_NewUser.setText("New User");
    Library_NewUser.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Library_NewUserActionPerformed(evt);
      }
    });

    Library_ViewFines.setText("View Fines");
    Library_ViewFines.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Library_ViewFinesActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(Library_CI, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(486, 486, 486)
                        .addComponent(Library_CO))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Library_ViewFines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Library_NewUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(107, 107, 107))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Library_CI, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Library_CO, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117)
                .addComponent(Library_NewUser)
                .addGap(38, 38, 38)
                .addComponent(Library_ViewFines)
                .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void Library_CIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Library_CIActionPerformed
    CheckIn ci = new CheckIn();
    ci.setVisible(true);
  }//GEN-LAST:event_Library_CIActionPerformed

  private void Library_COActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Library_COActionPerformed
    CheckOut co = new CheckOut();
    co.setVisible(true);
  }//GEN-LAST:event_Library_COActionPerformed

  private void Library_NewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Library_NewUserActionPerformed
    NewUser nu = new NewUser();
    nu.setVisible(true);
  }//GEN-LAST:event_Library_NewUserActionPerformed

  private void Library_ViewFinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Library_ViewFinesActionPerformed
    //update the fines before we get the list of fines
    String updateFinesQuery = "INSERT INTO fines(loan_id, fine_amt) "
        + "SELECT Book_Loans.loan_id, (CURRENT_DATE - (Book_Loans.due_date)) * 0.25 "
        + "AS calcualted_fine_amt FROM Book_Loans "
        + "WHERE Book_Loans.date_in IS NULL "
        + "AND CURRENT_DATE > Book_Loans.due_date "
        + "GROUP BY Book_Loans.loan_id, Book_Loans.due_date "
        + "HAVING CURRENT_DATE - (Book_Loans.due_date) > 0 "
        + "ON CONFLICT (loan_id) DO UPDATE "
        + "SET fine_amt = excluded.fine_amt ";

    try (Connection conn = connect(); PreparedStatement pstmt = conn.prepareStatement(updateFinesQuery)) {
      ResultSet rs = pstmt.executeQuery();
    } catch (SQLException ex) {
      System.out.println(ex.getMessage());
    }

    List<Fine> finesList = new ArrayList<>();

    String getListOfUnpaidFines = "SELECT Bname, bname_last, Borrower.card_id,"
        + " SUM(Fines.fine_amt) AS total_amt, is_paid FROM fines "
        + "JOIN Book_Loans ON fines.loan_id = Book_Loans.loan_id "
        + "JOIN Borrower ON Book_Loans.card_id = Borrower.card_id "
        + "WHERE NOT fines.is_paid "
        + "GROUP BY Borrower.card_id, Borrower.Bname, Borrower.bname_last, is_paid ";

    try (Connection conn = connect(); PreparedStatement pstmt = conn.prepareStatement(getListOfUnpaidFines)) {
      ResultSet rs = pstmt.executeQuery();

      while(rs.next()) {
        Fine fine = new Fine();
        Borrower borrower = new Borrower();

        fine.setFineAmt(rs.getDouble("total_amt"));
        fine.setPaid(false);

        borrower.setBname(rs.getString("Bname"));
        borrower.setBnameLast(rs.getString("Bname_last"));
        borrower.setCardId(rs.getInt("card_id"));

        fine.setBorrower(borrower);

        finesList.add(fine);
      }

    } catch (SQLException ex) {
      System.out.println(ex.getMessage());
    }

    Fines f = new Fines(finesList);
    f.setVisible(true);
  }//GEN-LAST:event_Library_ViewFinesActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Library().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton Library_CI;
  private javax.swing.JButton Library_CO;
  private javax.swing.JButton Library_NewUser;
  private javax.swing.JButton Library_ViewFines;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
